# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0004_delete_tasks'),
        ('appointments', '0002_auto_20171118_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='users_joining',
            field=models.ManyToManyField(related_name='appointments_joined', to='belt_exam.User'),
        ),
    ]
